### PR TITLE
Share profile

### PR DESCRIPTION
**Pull request by riteshsp2000**
1. Add share profile button
2 Hide signin and share button while viewing p when opened from URL

### CODE REVIEW

**Comment by DesignrKnight** [comment]
@riteshsp2000 , can you fetch and resolve conflicts?

**Comment by HarishTeens** [comment]
@riteshsp2000 please fix the conflicts

**Comment by DesignrKnight** [comment]
@HarishTeens 
Review and merge

**Review by DesignrKnight — APPROVED** [review]

**Comment by HarishTeens** [comment]
Finally we're all set for the event. Thanks for your PR @riteshsp2000

**Pull request merged**
